### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by MagnusSWE** [mike61988/magento2-dev-dk#25]
Hi! Running docker-compose -f docker-compose_windows.yml up -d gives the following on step 3:

[...]
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires magento/product-community-edition 2.3.4 -> satisfiable by magento/product-community-edition[2.3.4].
    - magento/product-community-edition 2.3.4 requires magento/composer ~1.5.0 -> satisfiable by magento/composer[1.5.0, 1.5.1] from composer repo (https://repo.packagist.org) but magento/composer[1.0.2, ..., 1.6.0] from composer repo (https://repo.magento.com) has higher repository priority. The packages with higher priority do not match your constraint and are therefore not installable. See https://getcomposer.org/repoprio for details and assistance.
  Problem 2
    - Root composer.json requires dealerdirect/phpcodesniffer-composer-installer ^0.5.0 -> satisfiable by dealerdirect/phpcodesniffer-composer-installer[v0.5.0].
    - dealerdirect/phpcodesniffer-composer-installer v0.5.0 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.

You are using Composer 2, which some of your plugins seem to be incompatible with. Make sure you update your plugins or report a plugin-issue to ask them to support Composer 2.
Service 'm23' failed to build : The command '/bin/sh -c composer create-project --repository=https://repo.magento.com/ magento/project-community-edition=2.3.4 /var/www/html/magento2ce/' returned a non-zero code: 2

**Comment by MagnusSWE** [comment]
This solution worked just fine, thanks! :-)

**Comment by lfolco** [comment]
@mike61988 can you update the environment to use composer 1?

**Comment by FullStackJohnMack** [comment]
This workaround did not work for me but I have been frantically installing/uninstalling different versions of Composer before I was directed here by @lfolco
